version: '3'

services:
  readings-postgres:
    image: readings-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: readings
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8085:8080"
    depends_on:
      - readings-postgres

  dailyrjava:
    image: dailyrjava
    restart: always
    ports:
      - "8086:8086"
    depends_on:
      - readings-postgres
