version: '3'

services:
  readings-postgres:
    image: dockerdoc83/readings-postgres:v1.0_linux
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: readings
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8085:8080"
    depends_on:
      - readings-postgres

  dailyrjava:
    image: dockerdoc83/dailyrjava:v1.10_linux
    restart: always
    ports:
      - "443:443"
    depends_on:
      - readings-postgres
